config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'home#top'

  resources :users, only: %i[index show edit update]
  get 'users/:id/doing', to: 'users#doing', as: 'doing'
  get 'users/:id/done', to: 'users#done', as: 'done'
  post 'change_status', to: 'users#change_task_status', as: 'change_task_status'
  get 'notification_login', to: 'users#notification_login'

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :tutorials

  namespace :tutorials do
    namespace :ranks do
      get :pv
      get :iine
      get :month_pv
      get :month_iine
      get :all_period_pv
      get :all_period_iine
    end
  end

  post 'tutorials/:id', to: 'tutorials#make_own_tutorial'
  get 'tags/:tag', to: 'tutorials#index', as: :tag

  # お問い合わせ
  get 'inquiries/new'
  post 'inquiries/confirm'
  post 'inquiries/complete'
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
  has_many :user_tutorials, foreign_key: 'tutorial_id'
  has_many :users, through: :user_tutorials
  accepts_nested_attributes_for :user_tutorials
  acts_as_taggable
  is_impressionable
  paginates_per 12

  scope :week_post, -> { where('created_at > ?', 7.days.ago )}
  scope :month_post, -> { where('created_at > ?', 1.month.ago )}

  def iine?(user)
    users.include?(user)
  end

  def self.search(keyward)
    where(['title LIKE ?', "%#{keyward}%"])
  end
end

app/controllers/tutorials/ranks_controller.rb
class Tutorials::RanksController < TutorialsController
  before_action :set_default_rank_tutorials
  def pv
    @tutorials = @default_rank_tutorials.week_post.sort_by { |t| t.impressionist_count }.reverse
  end

  def iine
    @tutorials = @default_rank_tutorials.week_post.sort_by { |t| t.users.count }.reverse
  end

  def month_pv
    @tutorials = @default_rank_tutorials.month_post.sort_by { |t| t.impressionist_count }.reverse
  end

  def month_iine
    @tutorials = @default_rank_tutorials.month_post.sort_by { |t| t.users.count }.reverse
  end

  def all_period_pv
    @tutorials = @default_rank_tutorials.sort_by { |t| t.impressionist_count }.reverse
  end

  def all_period_iine
    @tutorials = @default_rank_tutorials.sort_by { |t| t.users.count }.reverse
  end

  private

  def set_default_rank_tutorials
    @default_rank_tutorials = Tutorial.includes(:users, :taggings).page
  end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  before_action :set_tutorial, only: [:show, :edit, :update, :destroy, :make_own_tutorial]
  before_action  :set_available_tags_to_gon
  before_action  :set_tags, only: [:index, :show, :pv, :iine, :month_pv, :month_iine, :all_period_pv, :all_period_iine]
  # impressionist :actions=> [:show] unique指定を無視して走ってしまうのでコメントアウト

  def index
    if params[:tag]
      @tutorials = Tutorial.tagged_with(params[:tag]).order(created_at: :desc)
      @tutorials = @tutorials.page(params[:page])
    elsif params[:search]
      @tutorials = Tutorial.search(params[:search]).order(created_at: :desc)
      @tutorials = @tutorials.page(params[:page])
    else
      @tutorials = Tutorial.includes(:users, :tags, :taggings).order(created_at: :desc) # 新規投稿順
      @tutorials = @tutorials.page(params[:page])
    end
  end

  def show
    impressionist(@tutorial, nil, :unique => [:session_hash])
  end

  def new
    @tutorial = Tutorial.new
  end

  def create
    @tutorial = Tutorial.new(tutorial_params)
    @tutorial.ogp_url, @tutorial.ogp_description = get_ogp(@tutorial.url)
    if @tutorial.save
      redirect_to root_path
    else
      session[:error] = @tutorial.errors.full_messages
      redirect_to new_tutorial_path
    end
  end

  def make_own_tutorial
    redirect_to notification_login_path and return unless user_signed_in?

    if UserTutorial.where('user_id = ? and tutorial_id =?', current_user.id, @tutorial.id).blank?
      current_user.tutorials << @tutorial
    else
      UserTutorial.where('user_id = ? and tutorial_id =?', current_user.id, @tutorial.id).delete_all
    end
    redirect_to request.referer
  end

  def set_available_tags_to_gon
    gon.available_tags = Tutorial.tags_on(:tags).pluck(:name)
  end

  private
    def set_tutorial
      @tutorial = Tutorial.find(params[:id])
    end

    def set_tags
      @tags = Tutorial.tags_on(:tags)
    end

    def get_ogp(url)
      og = OpenGraph.new(url)
      og_image = og.images[0]
      unless og.images[0].include?('http')
        og_image = 'no-ogp-image.jpg'
      end
      return og_image, og.description
    end

    def tutorial_params
      params.require(:tutorial).permit(:title, :content, :url, :tag_list)
    end

    def set_tutorial_tags_to_gon
      gon.tutorial_tags = @tutorial.tag_list
    end
end

app/helpers/tutorials/ranks_helper.rb
module Tutorials::RanksHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/tutorials/ranks/_iine_tutorial_stack.html.slim
.border.rank-title
  h6
    i.fa.fa-trophy
    |  ランキング
    .rank-list-tab
      .btn-group.btn-group-sm aria-label=("Basic example") role="group"
        = link_to '1週間', tutorials_ranks_iine_path, type: 'button', class: 'btn', id: 'week'
        = link_to '1ヶ月', tutorials_ranks_month_iine_path, type: 'button', class: 'btn', id: 'month'
        = link_to 'ALL', tutorials_ranks_all_period_iine_path, type: 'button', class: 'btn', id: 'all'

- @tutorials.each do |tutorial|
  .media.border
    - if tutorial.ogp_url.blank?
      = image_tag 'no-ogp-image.jpg', size: '80x80'
    - else
      = image_tag tutorial.ogp_url, size: '80x80'
    .media-body
      = link_to tutorial, class: 'media-title' do
        h6.mt-0 = tutorial.title
      .iine-pv.d-flex.justify-content-end
        - tutorial.tag_list.each do |tag|
          label.btn-success.tutorial-tag
            = tag
        .posted_date
          = tutorial.created_at.strftime('%Y/%m/%d')
        .iine
          = link_to tutorial_path(tutorial), method: :post do
            - if tutorial.iine?(current_user)
              i.fa.fa-star.ml-2.star-blue
            - else
              i.fa.fa-star.ml-2.star-gray
          | #{tutorial.users.count}件
        .pv
          i.fa.fa-eye.ml-2.star-gray
          |  #{tutorial.impressionist_count} views

app/views/tutorials/ranks/_pv_tutorial_stack.html.slim
.border.rank-title
  h6
    i.fa.fa-trophy
    |  ランキング
    .rank-list-tab
      .btn-group.btn-group-sm aria-label=("Basic example") role="group"
        = link_to '1週間', tutorials_ranks_pv_path, type: 'button', class: 'btn', id: 'week'
        = link_to '1ヶ月', tutorials_ranks_month_pv_path, type: 'button', class: 'btn', id: 'month'
        = link_to 'ALL', tutorials_ranks_all_period_pv_path, type: 'button', class: 'btn', id: 'all'

- @tutorials.each do |tutorial|
  .media.border
    - if tutorial.ogp_url.blank?
      = image_tag 'no-ogp-image.jpg', size: '80x80'
    - else
      = image_tag tutorial.ogp_url, size: '80x80'
    .media-body
      = link_to tutorial, class: 'media-title' do
        h6.mt-0 = tutorial.title
      .iine-pv.d-flex.justify-content-end
        - tutorial.tag_list.each do |tag|
          label.btn-success.tutorial-tag
            = tag
        .posted_date
          = tutorial.created_at.strftime('%Y/%m/%d')
        .iine
          = link_to tutorial_path(tutorial), method: :post do
            - if tutorial.iine?(current_user)
              i.fa.fa-star.ml-2.star-blue
            - else
              i.fa.fa-star.ml-2.star-gray
          | #{tutorial.users.count}件
        .pv
          i.fa.fa-eye.ml-2.star-gray
          |  #{tutorial.impressionist_count} views

app/views/tutorials/ranks/_rank_list.html.slim
ul.list-group
  = link_to tutorials_path do
    li.list-group-item.text-dark#timeline
      i.fa.fa-calendar.ml-2
      | タイムライン
  = link_to tutorials_ranks_iine_path do
    li.list-group-item.text-dark#iine-rank
      i.fa.fa-star.ml-2
      | いいねランキング
  = link_to tutorials_ranks_pv_path do
    li.list-group-item.text-dark#pv-rank
      i.fa.fa-eye.ml-2
      | PVランキング

app/views/tutorials/ranks/_tutorial_stack.html.slim
.media.border
  | ランキング
- @tutorials.each do |tutorial|
  .media.border
    - if tutorial.ogp_url.blank?
      = image_tag 'no-ogp-image.jpg', size: '80x80'
    - else
      = image_tag tutorial.ogp_url, size: '80x80'
    .media-body
      = link_to tutorial, class: 'media-title' do
        h6.mt-0 = tutorial.title
      .iine-pv.d-flex.justify-content-end
        - tutorial.tag_list.each do |tag|
          label.btn-success.tutorial-tag
            = tag
        .posted_date
          = tutorial.created_at.strftime('%Y/%m/%d')
        .iine
          = link_to tutorial_path(tutorial), method: :post do
            - if tutorial.iine?(current_user)
              i.fa.fa-star.ml-2.star-blue
            - else
              i.fa.fa-star.ml-2.star-gray
          | #{tutorial.users.count}件
        .pv
          i.fa.fa-eye.ml-2.star-gray
          |  #{tutorial.impressionist_count} views

app/views/tutorials/ranks/all_period_iine.html.slim
.row
  .col-md-2.side-selector
    = render 'rank_list'
  .col-md-8.rank-list
    section
      /! Grid row
      = render 'iine_tutorial_stack'

  .col-md-2
    ul.list-group
      li.list-group-item.bg-info.text-white カテゴリー
      - @tags.each do |tag|
        = link_to tag_path(tag.name), class: 'text-dark' do
          li.list-group-item.text-dark
            = tag.name
            label.tutorial-tag-count
              = tag.taggings_count

app/views/tutorials/ranks/all_period_pv.html.slim
.row
  .col-md-2.side-selector
    = render 'rank_list'
  .col-md-8.rank-list
    section
      /! Grid row
      = render 'pv_tutorial_stack'

  .col-md-2
    ul.list-group
      li.list-group-item.bg-info.text-white カテゴリー
      - @tags.each do |tag|
        = link_to tag_path(tag.name), class: 'text-dark' do
          li.list-group-item.text-dark
            = tag.name
            label.tutorial-tag-count
              = tag.taggings_count

app/views/tutorials/ranks/iine.html.slim
.row
  .col-md-2.side-selector
    = render 'rank_list'
  .col-md-8.rank-list
    section
      /! Grid row
      = render 'iine_tutorial_stack'
  .col-md-2
    ul.list-group
      li.list-group-item.bg-info.text-white カテゴリー
      - @tags.each do |tag|
        = link_to tag_path(tag.name), class: 'text-dark' do
          li.list-group-item.text-dark
            = tag.name
            label.tutorial-tag-count
              = tag.taggings_count

app/views/tutorials/ranks/iine_rank.html.slim
.row
  .col-md-10
    section.text-center
      /! Grid row
      = render 'tutorial'

  .col-md-2
    ul.list-group
      li.list-group-item.bg-info.text-white カテゴリー
      - @tags.each do |tag|
        = link_to tag_path(tag.name), class: 'text-dark' do
          li.list-group-item.text-dark
            = tag.name
            label.tutorial-tag-count
              = tag.taggings_count

app/views/tutorials/ranks/month_iine.html.slim
.row
  .col-md-2.side-selector
    = render 'rank_list'
  .col-md-8.rank-list
    section
      /! Grid row
      = render 'iine_tutorial_stack'

  .col-md-2
    ul.list-group
      li.list-group-item.bg-info.text-white カテゴリー
      - @tags.each do |tag|
        = link_to tag_path(tag.name), class: 'text-dark' do
          li.list-group-item.text-dark
            = tag.name
            label.tutorial-tag-count
              = tag.taggings_count

app/views/tutorials/ranks/month_pv.html.slim
.row
  .col-md-2.side-selector
    ul.list-group
      = render 'rank_list'
  .col-md-8.rank-list
    section
      /! Grid row
      = render 'pv_tutorial_stack'

  .col-md-2
    ul.list-group
      li.list-group-item.bg-info.text-white カテゴリー
      - @tags.each do |tag|
        = link_to tag_path(tag.name), class: 'text-dark' do
          li.list-group-item.text-dark
            = tag.name
            label.tutorial-tag-count
              = tag.taggings_count

app/views/tutorials/ranks/pv.html.slim
.row
  .col-md-2.side-selector
    = render 'rank_list'
  .col-md-8.rank-list
    section
      /! Grid row
      = render 'pv_tutorial_stack'

  .col-md-2
    ul.list-group
      li.list-group-item.bg-info.text-white カテゴリー
      - @tags.each do |tag|
        = link_to tag_path(tag.name), class: 'text-dark' do
          li.list-group-item.text-dark
            = tag.name
            label.tutorial-tag-count
              = tag.taggings_count

app/views/tutorials/ranks/pv_rank.html.slim
.row
  .col-md-10
    section.text-center
      /! Grid row
      = render 'tutorials/tutorial'

  .col-md-2
    ul.list-group
      li.list-group-item.bg-info.text-white カテゴリー
      - @tags.each do |tag|
        = link_to tag_path(tag.name), class: 'text-dark' do
          li.list-group-item.text-dark
            = tag.name
            label.tutorial-tag-count
              = tag.taggings_count