config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'home#top'

  resources :users, only: %i[index show edit update]
  get 'users/:id/doing', to: 'users#doing', as: 'doing'
  get 'users/:id/done', to: 'users#done', as: 'done'
  post 'change_status', to: 'users#change_task_status', as: 'change_task_status'
  get 'notification_login', to: 'users#notification_login'

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :tutorials

  namespace :tutorials do
    namespace :ranks do
      get :pv
      get :iine
      get :month_pv
      get :month_iine
      get :all_period_pv
      get :all_period_iine
    end
  end

  post 'tutorials/:id', to: 'tutorials#make_own_tutorial'
  get 'tags/:tag', to: 'tutorials#index', as: :tag

  # お問い合わせ
  get 'inquiries/new'
  post 'inquiries/confirm'
  post 'inquiries/complete'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  has_many :social_profiles, dependent: :destroy
  has_many :user_tutorials, foreign_key: 'user_id'
  has_many :tutorials, through: :user_tutorials

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i(github)
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include OAuthService
  # callback for google
  def github
    callback_for(:github)
  end

  # common callback method
  def callback_for(provider)
    # @user = User.from_omniauth(request.env["omniauth.auth"])
    @user = OAuthService::GetOAuthUser.call(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :done, :doing]

  def index
    @users = User.all
  end

  def show
    @mytutorials = @user.tutorials.includes(:taggings, :users)
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def notification_login
  end

  def change_task_status
    status = current_user.user_tutorials.find_by(tutorial_id: params[:tutorial_id]).is_done
    if status == 0
      current_user.user_tutorials.find_by(tutorial_id: params[:tutorial_id]).update(is_done: 1)
    else
      current_user.user_tutorials.find_by(tutorial_id: params[:tutorial_id]).update(is_done: 0)
    end
    redirect_to request.referer
  end

  def done
    @mytutorials = set_user_tutorials.where(user_tutorials: {is_done: 1})
  end

  def doing
    @mytutorials = set_user_tutorials.where(user_tutorials: {is_done: 0})
  end

  private
  def set_user_tutorials
    User.find(params[:id]).tutorials.includes(:user_tutorials, :taggings, :users)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :description)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
= form_with(model: user, local: true) do |form|
  - if user.errors.any?
    #error_explanation
      h2
        = pluralize(user.errors.count, "error")
        | prohibited this menu from being saved:
      ul
        - user.errors.full_messages.each do |message|
          li= message

  .field
    = form.label :name
    = form.text_field :name, class: 'form-control'

  .field
    = form.label :description
    = form.text_field :description, class: 'form-control'

  = form.submit '更新', class: 'btn btn-primary'

app/views/users/_user_list.html.slim
ul.list-group
  - @users.each do |user|
    = link_to user do
      li.list-group-item.user-group
        .user-image
          = image_tag user.social_profiles.find_by(provider: 'github').image_url, size: '60x60'
        .user-content
          h5
            = user.name
          p
            = user.description

app/views/users/doing.html.slim
.row
  .col-md-3.mb-4
    = image_tag @user.social_profiles.find_by(provider: 'github').image_url, size: '200x200'
  .col-md-6.user-name
    h3
      = @user.name
    p
      = @user.description
/ .col-md-6.mb-4

hr
.row.mytutorial
  .col-md-4
    = link_to @user do
      .alert.alert-primary.mytutorial-title role="alert"
        strong マイチュートリアル
  .col-md-4
    = link_to done_path do
      .alert.alert-success.mytutorial-title
        strong やったもの
  .col-md-4
    = link_to doing_path do
      .alert.alert-danger.mytutorial-title
        strong まだやってない
.jumbotron.mytutorial-doing
  - @mytutorials.each do |tutorial|
    .card.mytutorial-card
      .card-header
        = tutorial.title
      .card-body.user-body
        p.card-text
          - if tutorial.ogp_url.blank?
            = image_tag 'no-ogp-image.jpg', size: '80x80'
          - else
            = image_tag tutorial.ogp_url, size: '80x80'
        .detail-container
          - tutorial.tag_list.each do |tag|
            label.btn-success.tutorial-tag
              = tag
          p.content
            = tutorial.content
          = link_to tutorial, class: 'btn-sm btn-primary btn-md' do
            | 詳細
          = link_to "#{tutorial.url}", class: 'btn-sm btn-primary btn-md' do
            | チュートリアル
        - if tutorial.iine?(current_user)
          = link_to tutorial_path(tutorial), method: :post, class: 'btn btn-danger btn-md favorite' do
            | お気に入り解除
            i.fa.fa-ban.ml-2
        - else
          = link_to tutorial_path(tutorial), method: :post, class: 'btn btn-info btn-md favorite' do
            | お気に入り登録
            i.fa.fa-star.ml-2
        - if @user == current_user
          = link_to change_task_status_path(params: {tutorial_id: tutorial}), method: :post, class: 'btn btn-info btn-md done' do
            | 完了
            i.fa.fa-check.ml-2

app/views/users/done.html.slim
.row
  .col-md-3.mb-4
    = image_tag @user.social_profiles.find_by(provider: 'github').image_url, size: '200x200'
  .col-md-6.user-name
    h3
      = @user.name
    p
      = @user.description
/ .col-md-6.mb-4

hr
.row.mytutorial
  .col-md-4
    = link_to @user do
      .alert.alert-primary.mytutorial-title role="alert"
        strong マイチュートリアル
  .col-md-4
    = link_to done_path do
      .alert.alert-success.mytutorial-title
        strong やったもの
  .col-md-4
    = link_to doing_path do
      .alert.alert-danger.mytutorial-title
        strong まだやってない
.jumbotron.mytutorial-done
  - @mytutorials.each do |tutorial|
    .card.mytutorial-card
      .card-header
        = tutorial.title
      .card-body.user-body
        p.card-text
          - if tutorial.ogp_url.blank?
            = image_tag 'no-ogp-image.jpg', size: '80x80'
          - else
            = image_tag tutorial.ogp_url, size: '80x80'
        .detail-container
          - tutorial.tag_list.each do |tag|
            label.btn-success.tutorial-tag
              = tag
          p.content
            = tutorial.content
          = link_to tutorial, class: 'btn-sm btn-primary btn-md' do
            | 詳細
          = link_to "#{tutorial.url}", class: 'btn-sm btn-primary btn-md' do
            | チュートリアル
        - if tutorial.iine?(current_user)
          = link_to tutorial_path(tutorial), method: :post, class: 'btn btn-danger btn-md favorite' do
            | お気に入り解除
            i.fa.fa-ban.ml-2
        - else
          = link_to tutorial_path(tutorial), method: :post, class: 'btn btn-info btn-md favorite' do
            | お気に入り登録
            i.fa.fa-star.ml-2
        - if @user == current_user
          = link_to change_task_status_path(params: { tutorial_id: tutorial }), method: :post, class: 'btn btn-md done doing-again' do
            | やってない
        i.fa.fa-graduation-cap.ml-2

app/views/users/edit.html.slim
h2 Edit User

= image_tag @user.social_profiles.find_by(provider: 'github').image_url, size: '80x80'

= render 'form', user: @user

app/views/users/index.html.slim
.row
  .col-md-2
  .col-md-8.rank-list
    section
      /! Grid row
      = render 'user_list'
  .col-md-2

app/views/users/notification_login.html.slim
.jumbotron.hero
  = image_tag 'home/CODEROAD-logo.png'
  p.lead
    | お気に入り機能を使用するには、Githubログインが必要です
  hr.my-2/
  p
    - if user_signed_in?
      | チュートリアル一覧を確認して見ましょう
    - else
      | さあ、まずはGitHubアカウントでログインしましょう
  p.lead
    - if user_signed_in?
      = link_to 'チュートリアル一覧へ', tutorials_path , class: 'btn btn-primary'
      = link_to 'トレンドいいねランキング', tutorials_ranks_iine_path, class: 'btn btn-primary'
    - else
      = link_to '/users/auth/github', class: 'btn btn-primary' do
        i.fa.fa-github.mr-2
        | GitHubログイン

app/views/users/show.html.slim
.row
  .col-md-3.mb-4
    = image_tag @user.social_profiles.find_by(provider: 'github').image_url, size: '200x200'
  .col-md-6.user-name
    h3
      = @user.name
    p
      = @user.description
  / .col-md-6.mb-4

hr
.row.mytutorial
  .col-md-4
    = link_to @user do
      .alert.alert-primary.mytutorial-title role="alert"
        strong マイチュートリアル
  .col-md-4
    = link_to done_path do
      .alert.alert-success.mytutorial-title
        strong やったもの
  .col-md-4
    = link_to doing_path do
      .alert.alert-danger.mytutorial-title
        strong まだやってない
.jumbotron.mytutorial-tron
  - @mytutorials.each do |tutorial|
    .card.mytutorial-card
      .card-header
        = tutorial.title
      .card-body.user-body
        p.card-text
          - if tutorial.ogp_url.blank?
            = image_tag 'no-ogp-image.jpg', size: '80x80'
          - else
            = image_tag tutorial.ogp_url, size: '80x80'
        .detail-container
          - tutorial.tag_list.each do |tag|
            label.btn-success.tutorial-tag
              = tag
          p.content
            = tutorial.content
          = link_to tutorial, class: 'btn-sm btn-primary btn-md' do
            | 詳細
          = link_to "#{tutorial.url}", class: 'btn-sm btn-primary btn-md' do
            | チュートリアル
        - if tutorial.iine?(current_user)
          = link_to tutorial_path(tutorial), method: :post, class: 'btn btn-danger btn-md favorite' do
            | お気に入り解除
            i.fa.fa-ban.ml-2
        - else
          = link_to tutorial_path(tutorial), method: :post, class: 'btn btn-info btn-md favorite' do
            | お気に入り登録
            i.fa.fa-star.ml-2
        - if @user == current_user
          = link_to change_task_status_path(params: { tutorial_id: tutorial }), method: :post, class: 'btn btn-info btn-md done' do
            | 完了
            i.fa.fa-check.ml-2