config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'home#top'

  resources :users, only: %i[index show edit update]
  get 'users/:id/doing', to: 'users#doing', as: 'doing'
  get 'users/:id/done', to: 'users#done', as: 'done'
  post 'change_status', to: 'users#change_task_status', as: 'change_task_status'
  get 'notification_login', to: 'users#notification_login'

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :tutorials

  namespace :tutorials do
    namespace :ranks do
      get :pv
      get :iine
      get :month_pv
      get :month_iine
      get :all_period_pv
      get :all_period_iine
    end
  end

  post 'tutorials/:id', to: 'tutorials#make_own_tutorial'
  get 'tags/:tag', to: 'tutorials#index', as: :tag

  # お問い合わせ
  get 'inquiries/new'
  post 'inquiries/confirm'
  post 'inquiries/complete'
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
    @inquiry = Inquiry.new
  end

  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      render action: 'confirm'
    else
      render action: 'new'
    end
  end

  def complete
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.save

    else

    end
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/inquiries/_form.html.slim
= form_with(model: inquiry, url: inquiries_confirm_path, local:true) do |f|
  - if inquiry.errors.any?
    .alert.alert-danger
      strong 入力内容にエラーがあります
      ul
        - inquiry.errors.each do |attr, msg|
          li = "#{attr}#{msg}"

  .form-group
    = f.label :name
    = f.text_field :name, placeholder: '名前', class: 'form-control'
  .form-group
    = f.label :email
    = f.email_field :email, placeholder: 'email', class: 'form-control'
  .form-group
    = f.label :message
    = f.text_area :message, placeholder: 'お問い合わせ内容', class: 'form-control', rows: 10
  .form-group
    = f.submit '確認', class: 'btn btn-primary'

app/views/inquiries/complete.html.slim
p お問い合わせが完了しました。
p ご意見ありがとうございます。

app/views/inquiries/confirm.html.slim
h1 お問い合わせ内容確認

= form_with(model: @inquiry, url: inquiries_complete_path, local: true) do |f|
  .form-group
    = f.label :name
    = @inquiry.name
    = f.hidden_field :name
  .form-group
    = f.label :email
    = @inquiry.email
    = f.hidden_field :email
  .form-group
    = f.label :message
    = simple_format(@inquiry.message)
    = f.hidden_field :message
  .form-group
    = f.submit '送信', class: 'btn btn-primary'
    = link_to '戻る', inquiries_new_path, class: 'btn btn-success'

app/views/inquiries/new.html.slim
h1 お問い合わせ

= render 'form', inquiry: @inquiry