config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'home#top'

  resources :users, only: %i[index show edit update]
  get 'users/:id/doing', to: 'users#doing', as: 'doing'
  get 'users/:id/done', to: 'users#done', as: 'done'
  post 'change_status', to: 'users#change_task_status', as: 'change_task_status'
  get 'notification_login', to: 'users#notification_login'

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :tutorials

  namespace :tutorials do
    namespace :ranks do
      get :pv
      get :iine
      get :month_pv
      get :month_iine
      get :all_period_pv
      get :all_period_iine
    end
  end

  post 'tutorials/:id', to: 'tutorials#make_own_tutorial'
  get 'tags/:tag', to: 'tutorials#index', as: :tag

  # お問い合わせ
  get 'inquiries/new'
  post 'inquiries/confirm'
  post 'inquiries/complete'
end

app/views/layouts/_footer.html.slim
footer.page-footer.text-center.font-small.mdb-color.darken-2.mt-4.wow.fadeIn
  /! Call to action
  .pt-4
    = link_to '/#about', role:'button', target: '_blank', class: 'btn btn-outline-white'
      | About this apps
      i.fa.fa-book.ml-2
    = link_to inquiries_new_path, role:'button', class: 'btn btn-outline-white'
      | お問い合わせ
      i.fa.fa-phone-square.ml-2
  /! /.Call to action
  hr.my-4/
  /! Social icons
  .pb-4
    a href="https://taigamikami.github.io/" target="_blank"
      | Made by Taiga Mikami
  .footer-copyright.py-3
    | © 2018 Copyright:
    a href="https://mdbootstrap.com/bootstrap-tutorial/" Gutty on Rails

app/views/layouts/_header.html.slim
/! Main Navigation
header
  /! Navbar
  nav.navbar.fixed-top.navbar-expand-lg.navbar-light.white.scrolling-navbar
    .container
      /! Brand
      = link_to root_path, class: 'navbar-brand waves-effect'
        = image_tag 'logo.png', size: '24x20', class: 'header-logo'
        strong.blue-text CODEROAD
      /! Collapse
      button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button"
        span.navbar-toggler-icon
      /! Links
      #navbarSupportedContent.collapse.navbar-collapse
        /! Left
        ul.navbar-nav.mr-auto
          li.nav-item.dropdown
            a.nav-link.dropdown-toggle.border.border-light.waves-effect aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#!" role="button"
              | チュートリアル
            .dropdown-menu
              = link_to tutorials_path, class: 'dropdown-item' do
                i.fa.fa-calendar.ml-2
                |  タイムライン
              = link_to tutorials_ranks_iine_path, class: 'dropdown-item' do
                  i.fa.fa-star.ml-2
                  |  いいねランキング
              = link_to tutorials_ranks_pv_path, class: 'dropdown-item' do
                  i.fa.fa-eye.ml-2
                  |  PVランキング
          li.nav-item.dropdown
            a.nav-link.dropdown-toggle.border.border-light.waves-effect aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#!" role="button"
              | コミュニティ
            .dropdown-menu
              = link_to users_path, class: 'dropdown-item' do
                i.fa.fa-users.ml-2
                |  ユーザー一覧
          li.nav-item
            = link_to '新規投稿', new_tutorial_path, class: 'nav-link border border-light'
          li.nav-item.search-form
            = form_tag tutorials_path, method: 'get' do
              i.fa.fa-search.mr-2
              = text_field_tag :search, params[:search], placeholder: 'キーワード', class: 'form-control'
              = submit_tag '検索', class: 'btn btn-primary btn-md btn-search'

        /! Right
        ul.navbar-nav.nav-flex-icons
          li.nav-item.dropdown
            - if user_signed_in?
              a.nav-link.dropdown-toggle.border.border-light.rounded.waves-effect aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#!" role="button"
                = image_tag current_user.social_profiles.find_by(provider: "github").image_url, size: '32x32', class: 'github-image'
              .dropdown-menu
                = link_to 'マイページ', current_user , class: 'dropdown-item'
                = link_to 'プロフィール編集', edit_user_path(current_user) , class: 'dropdown-item'
                = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'dropdown-item'
            - else
              = link_to '/users/auth/github', class: 'nav-link border border-light rounded waves-effect' do
                i.fa.fa-github.mr-2
                | GitHubログイン

app/views/layouts/application.html.slim
doctype html
html lang="ja"
  head
    title
      | Coderoad
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag('favicon/favicon.ico')
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag @individual_assets = "#{controller_name}/application", media: 'all' if asset_exist? "javascripts/#{@individual_assets}"
    = include_gon
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag  @individual_assets = "#{controller_name}/application" if asset_exist? "javascripts/#{@individual_assets}"
    link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
  body
    = render 'layouts/header'
    main.mt-5.pt-5
      .container
        = yield
    = render 'layouts/footer'